//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class admin_users
    {

        [Required(ErrorMessage ="Please Provide UserName.",AllowEmptyStrings = false)]
        public string email { get; set; }
        public int id { get; set; }
        [Required(ErrorMessage ="Please Provide Password.",AllowEmptyStrings = false)]
        [DataType(DataType.Password)]
        public string password { get; set; }
    }
}
