//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class guaging_dia_types_guaging_machines_mapping
    {
        public int id { get; set; }
        public int guaging_dia_types_id { get; set; }
        public int guaging_machines_id { get; set; }
    }
}
