//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class saved_summary
    {
        public int id { get; set; }
        public string customer_name { get; set; }
        public string component_name { get; set; }
        public string opp_id { get; set; }
        public string data { get; set; }
        public System.DateTime date_time { get; set; }
    }
}
